# Generated by Django 2.1 on 2018-08-24 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='Nothing here')),
                ('title', models.TextField(default='Default title')),
                ('date', models.DateTimeField(auto_now=True, help_text='creation time')),
                ('img', models.ImageField(upload_to='media/articles/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'article_pl',
                'db_table': 'articles',
                'required_db_vendor': 'mysql',
            },
        ),
    ]
